import type { SensitiveHostCategory } from '../contract/types.js';

export const BUILTIN_HOSTS: Record<SensitiveHostCategory, readonly string[]> = {
  banking: [
    'bank',
    'bank.in',
    'chase.com',
    'bankofamerica.com',
    'wellsfargo.com',
    'citi.com',
    'citibank.com',
    'capitalone.com',
    'usbank.com',
    'pnc.com',
    'hsbc.com',
    'barclays.co.uk',
    'lloydsbank.com',
    'natwest.com',
    'santander.com',
    'ing.com',
    'hdfcbank.com',
    'icicibank.com',
    'onlinesbi.sbi',
    'sbi.co.in',
    'axisbank.com',
    'kotak.com',
  ],
  payments: [
    'paypal.com',
    'stripe.com',
    'wise.com',
    'venmo.com',
    'cash.app',
    'razorpay.com',
    'paytm.com',
    'phonepe.com',
    'pay.google.com',
    'payments.google.com',
    'pay.amazon.com',
    'klarna.com',
    'afterpay.com',
  ],
  webmail: [
    'mail.google.com',
    'outlook.live.com',
    'outlook.office.com',
    'outlook.office365.com',
    'mail.yahoo.com',
    'mail.proton.me',
    'app.fastmail.com',
    'mail.zoho.com',
  ],
  identity: [
    'accounts.google.com',
    'myaccount.google.com',
    'login.microsoftonline.com',
    'login.live.com',
    'account.microsoft.com',
    'account.live.com',
    'appleid.apple.com',
    'idmsa.apple.com',
    'icloud.com',
    'okta.com',
    'auth0.com',
    'onelogin.com',
    'duosecurity.com',
    'login.yahoo.com',
    'id.atlassian.com',
    'signin.aws.amazon.com',
    'accounts.firefox.com',
  ],
  government: [
    'gov',
    'mil',
    'gov.in',
    'nic.in',
    'gov.uk',
    'gc.ca',
    'gov.au',
    'govt.nz',
    'gouv.fr',
    'bund.de',
    'europa.eu',
  ],
  tax: ['turbotax.com', 'turbotax.intuit.com', 'hrblock.com', 'taxact.com', 'cleartax.in', 'quicko.com'],
  health: [
    'mychart.org',
    'myuhc.com',
    'anthem.com',
    'kaiserpermanente.org',
    'cvs.com',
    'walgreens.com',
    'labcorp.com',
    'questdiagnostics.com',
    'zocdoc.com',
    'teladoc.com',
    'nhs.uk',
    'practo.com',
    '1mg.com',
  ],
};

export const AUTH_PATH_RE = /(^|\/)(login|log-in|signin|sign-in|signup|sign-up|oauth2?|auth|sso|saml|2fa|mfa)(\/|$|[.?#])/i;
